pagopa/arc-fe-e2e

.env.dev, .gitignore, playwright.config.ts, tests/checkout-link.test.spec.ts
=> feat: [P4PU-489] Created test for payment notice button

tests/receipts-for-user.spec.ts
This test try to count the number of receipts showed on homepage
=> feat: [P4PU-493] Add test to count 

tests/receipts.spec.ts, utils.ts
Added a new E2E test about the receipt details page
- Added a new E2E test (receipt details page)
- Added a new function in utils (getFulfilledResponse) useful to inspect an upcoming response from an API call
- Added a new function in utils (isValidDate)
- Receipt details page inspection: consistency and data presence
We are adding a minimum number of E2E tests to minimize the occurrence of bugs and failures
Run:
=> feat: [P4PU-494] receipt details page E2E test

tests/logout.spec.ts
This pr adds the "logout flow" check
=> feat: [P4PU-488] Logout test

tests/checkout-link.test.spec.ts
This pr fixes the checkout link test to make it more flexible.
Run:
=> fix: [P4PU-528] Fixed checkout link to make it more flexible

tests/checkout-link.test.spec.ts
=> fix: [P4PU-528] Deleted useless code

tests/receipts-for-user-error.spec.ts
=> feat: [P4PU-556] Created test for receipts list error

tests/payment-notices.spec.ts
Add test on payment notices main page
=> feat: [P4PU-490] Add test on payment notices main page

tests/payment-notices.spec.ts
Add test for payment notice detail
=> feat: [P4PU-491] Add test for payment notice detail

.github/workflows/lint.yml, .prettierrc, eslint.config.mjs, package.json, playwright.config.ts, tests/checkout-link.test.spec.ts, tests/login.setup.ts, tests/logout.spec.ts, tests/my-data-test.spec.ts, tests/payment-notices.spec.ts, tests/post-auth-test.spec.ts, tests/receipts-for-user-error.spec.ts, tests/receipts.spec.ts, tests/submit-assistance-form.spec.ts, utils.ts, yarn.lock
- adds prettier
- adds eslint
- fixes linting and formatting problems
- adds linting github action
Run:
=> feat: [P4PU-551] formatting and linting

tests/receipts.spec.ts
Add a test in case of error in receipt detail
=> feat: [P4PU-557] Add a test in case of error in receipt detail

tests/payment-notices.spec.ts
Add unhappy path for empty list of receipts
=> feat: [P4PU-559] Add unhappy path for empty list of payment notices

tests/receipts.spec.ts
=> feat: [P4PU-559] Add test for empy list

tests/receipts.spec.ts
This PR fixes E2E tests related to this change https://github.com/pagopa/arc-fe/pull/167
Run:
=> fix: [P4PU-554] receipt.spec.ts test fix

tests/payment-notices.spec.ts
=> feat: [P4PU-492] Add checkout payment test

tests/login.setup.ts
This pr removes the click on "accetta tutti" button steps, since it was necessary for closing the cookie banner that has been removed from the tested repository.
- removes banner click from the login test
Run:
the tested functionality is not published on any environment at the date of this pr, this change can be tested on this pr branch https://github.com/pagopa/arc-fe/pull/176
=> feat: [P4PU-597] removes banner click from login test

tests/receipts.spec.ts
=> feat: [P4PU-601] Adapted receipt test to new api

tests/login.setup.ts, tests/my-data-test.spec.ts, tests/payment-notices.spec.ts, tests/receipts-for-user.spec.ts, tests/receipts.spec.ts
This PR add more "strictable" handles using id and test-id instead of "getText"
- Change handlers
Run:
=> feat: [P4PU-552] enhance test with id

playwright.config.ts
This change make possible parallel tests execution to speed up time
- playwright.config.ts file updated
Test execution in CI mode was very slow (now 50% faster)
Run:
=> ci: [P4PU-611] parallel CI E2E tests execution

tests/payment-notices.spec.ts
Removes dependency from browser storage to test the Payment notice functionality
- refactor notice tests into steps to mantain selected notice across test cases
Client no longer uses storage to mantain the selected PaymentNotice 
Run:
=> test: [P4PU-795] notice detail api

tests/login.setup.ts, tests/payment-notices.spec.ts, tests/receipts.spec.ts, tests/user.spec.ts
This change updates all assertions on routes/urls after that they were updated on the ARC's FE 
All assertion on routes/urls updated to reflect the new convention
This change is required because alle routes/urls on the ARC's FE were renamed (a business/design request)
Run:
=> feat: [P4PU-780] routes/urls update

tests/carts.spec.ts, tests/payment-notices.spec.ts, tests/receipts.spec.ts, utils/index.ts
This PR add new E2E tests related to a new FE functionality that introduces the cart UX
- Added E2E tests (happy and unhappy paths)
- Updated some E2E tests (minor fix as updating ids)
- Extracting the euro conversion function into a separate module
These new tests are required because we introduced a new functionality FE side that allows the cart experience and the payment of multiple notices in one transaction
Run:
=> feat: [P4PU-726] cart E2E tests introduction
